[[pprof]]
arch = "aarch64"
git-tree-sha1 = "4f25f14a36f9905355bac1f8ad90e06ace132e3d"
os = "macos"

    [[pprof.download]]
    sha256 = "318f3d7a22e6f34087636f475b9c1b440df0ba239a4ae1db291f4a15fbffdc2e"
    url = "https://github.com/JuliaBinaryWrappers/pprof_jll.jl/releases/download/pprof-v2.0.0+0/pprof.v2.0.0.aarch64-apple-darwin.tar.gz"
[[pprof]]
arch = "aarch64"
git-tree-sha1 = "1e3cfd458e66bf08cfc1d2c68b77edb1b28cf51c"
libc = "glibc"
os = "linux"

    [[pprof.download]]
    sha256 = "3e84e3e131eab3e2068f7ecd3cd951fdf1e06df8f6403067072569dda2dd1a8a"
    url = "https://github.com/JuliaBinaryWrappers/pprof_jll.jl/releases/download/pprof-v2.0.0+0/pprof.v2.0.0.aarch64-linux-gnu.tar.gz"
[[pprof]]
arch = "aarch64"
git-tree-sha1 = "1e3cfd458e66bf08cfc1d2c68b77edb1b28cf51c"
libc = "musl"
os = "linux"

    [[pprof.download]]
    sha256 = "3e84e3e131eab3e2068f7ecd3cd951fdf1e06df8f6403067072569dda2dd1a8a"
    url = "https://github.com/JuliaBinaryWrappers/pprof_jll.jl/releases/download/pprof-v2.0.0+0/pprof.v2.0.0.aarch64-linux-musl.tar.gz"
[[pprof]]
arch = "aarch64"
git-tree-sha1 = "12581697580596b733f195e6ce47fc6f2401c617"
os = "freebsd"

    [[pprof.download]]
    sha256 = "acc727cdbdcc43e28b7575c5c014f07b3bfc94e042d8e5f0d46d6ad50d6896a5"
    url = "https://github.com/JuliaBinaryWrappers/pprof_jll.jl/releases/download/pprof-v2.0.0+0/pprof.v2.0.0.aarch64-unknown-freebsd.tar.gz"
[[pprof]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "19e3f6c633e2d532e208f34834e71fe92da247e7"
libc = "glibc"
os = "linux"

    [[pprof.download]]
    sha256 = "a464179bb7a220190dae496972ccddd1ce28d6a24327ea6892e73c64d80b8542"
    url = "https://github.com/JuliaBinaryWrappers/pprof_jll.jl/releases/download/pprof-v2.0.0+0/pprof.v2.0.0.armv6l-linux-gnueabihf.tar.gz"
[[pprof]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "19e3f6c633e2d532e208f34834e71fe92da247e7"
libc = "musl"
os = "linux"

    [[pprof.download]]
    sha256 = "a464179bb7a220190dae496972ccddd1ce28d6a24327ea6892e73c64d80b8542"
    url = "https://github.com/JuliaBinaryWrappers/pprof_jll.jl/releases/download/pprof-v2.0.0+0/pprof.v2.0.0.armv6l-linux-musleabihf.tar.gz"
[[pprof]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "04ab04d95dec450ff5316b1ed2494b3dd622f76d"
libc = "glibc"
os = "linux"

    [[pprof.download]]
    sha256 = "0168d0d928054318442b31fa3728bd0ae5ae35836f4e298305740af379cca59e"
    url = "https://github.com/JuliaBinaryWrappers/pprof_jll.jl/releases/download/pprof-v2.0.0+0/pprof.v2.0.0.armv7l-linux-gnueabihf.tar.gz"
[[pprof]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "04ab04d95dec450ff5316b1ed2494b3dd622f76d"
libc = "musl"
os = "linux"

    [[pprof.download]]
    sha256 = "0168d0d928054318442b31fa3728bd0ae5ae35836f4e298305740af379cca59e"
    url = "https://github.com/JuliaBinaryWrappers/pprof_jll.jl/releases/download/pprof-v2.0.0+0/pprof.v2.0.0.armv7l-linux-musleabihf.tar.gz"
[[pprof]]
arch = "i686"
git-tree-sha1 = "5500326e30d990c3971fb63a3ca25a782f41799f"
libc = "glibc"
os = "linux"

    [[pprof.download]]
    sha256 = "efc495201e3b5b5619ab5955958c8fbe19deb84af2646dc21b730d8a04e0c83c"
    url = "https://github.com/JuliaBinaryWrappers/pprof_jll.jl/releases/download/pprof-v2.0.0+0/pprof.v2.0.0.i686-linux-gnu.tar.gz"
[[pprof]]
arch = "i686"
git-tree-sha1 = "5500326e30d990c3971fb63a3ca25a782f41799f"
libc = "musl"
os = "linux"

    [[pprof.download]]
    sha256 = "efc495201e3b5b5619ab5955958c8fbe19deb84af2646dc21b730d8a04e0c83c"
    url = "https://github.com/JuliaBinaryWrappers/pprof_jll.jl/releases/download/pprof-v2.0.0+0/pprof.v2.0.0.i686-linux-musl.tar.gz"
[[pprof]]
arch = "i686"
git-tree-sha1 = "9156df2308d7d717f1fdd106d291293de94b8c06"
os = "windows"

    [[pprof.download]]
    sha256 = "c14f42ef4577b3942e0bcb90216c7aef1276332e7291ed10f8558dc8d83793f3"
    url = "https://github.com/JuliaBinaryWrappers/pprof_jll.jl/releases/download/pprof-v2.0.0+0/pprof.v2.0.0.i686-w64-mingw32.tar.gz"
[[pprof]]
arch = "powerpc64le"
git-tree-sha1 = "ece4a69460b18f341041ee78fa16c38517b86f18"
libc = "glibc"
os = "linux"

    [[pprof.download]]
    sha256 = "959e7b651b3bbc68c21a7e296a3163a718ec64597f5ad075349da358b0f252d4"
    url = "https://github.com/JuliaBinaryWrappers/pprof_jll.jl/releases/download/pprof-v2.0.0+0/pprof.v2.0.0.powerpc64le-linux-gnu.tar.gz"
[[pprof]]
arch = "riscv64"
git-tree-sha1 = "929b208415109bde24d3aad459f34a937462fbcd"
libc = "glibc"
os = "linux"

    [[pprof.download]]
    sha256 = "c3e3835caf17e4ef6192238077cc8117fd99e69bf1fa546e99630f6d96d36b6a"
    url = "https://github.com/JuliaBinaryWrappers/pprof_jll.jl/releases/download/pprof-v2.0.0+0/pprof.v2.0.0.riscv64-linux-gnu.tar.gz"
[[pprof]]
arch = "x86_64"
git-tree-sha1 = "6bed8022b3c6e83a9e3880f41fde72eaaa9d173b"
os = "macos"

    [[pprof.download]]
    sha256 = "8ae10f77718553fe7ab46390141a5cc5b8340d1ca4cc3af23c4ef6d7c629be29"
    url = "https://github.com/JuliaBinaryWrappers/pprof_jll.jl/releases/download/pprof-v2.0.0+0/pprof.v2.0.0.x86_64-apple-darwin.tar.gz"
[[pprof]]
arch = "x86_64"
git-tree-sha1 = "579b2972c1e7b798ee4281dd37d60a362be0e1f5"
libc = "glibc"
os = "linux"

    [[pprof.download]]
    sha256 = "592ad438241380ed603967cb6a21bd38ccd01837b9ddc188a7c7be552d1f3d50"
    url = "https://github.com/JuliaBinaryWrappers/pprof_jll.jl/releases/download/pprof-v2.0.0+0/pprof.v2.0.0.x86_64-linux-gnu.tar.gz"
[[pprof]]
arch = "x86_64"
git-tree-sha1 = "3c2e269982aec59c569fe7f90f63338b28a66ae4"
libc = "musl"
os = "linux"

    [[pprof.download]]
    sha256 = "5692888c94278622467d29a3a381b9654aa478a3489a48ae368099f04684a519"
    url = "https://github.com/JuliaBinaryWrappers/pprof_jll.jl/releases/download/pprof-v2.0.0+0/pprof.v2.0.0.x86_64-linux-musl.tar.gz"
[[pprof]]
arch = "x86_64"
git-tree-sha1 = "80079797af29e8d4a71d54bf47bc990320bf341c"
os = "freebsd"

    [[pprof.download]]
    sha256 = "2a1248810faa7ebf0c0c19049e2ee9ba8191fec4f420830f1d9313b6f3fe7db5"
    url = "https://github.com/JuliaBinaryWrappers/pprof_jll.jl/releases/download/pprof-v2.0.0+0/pprof.v2.0.0.x86_64-unknown-freebsd.tar.gz"
[[pprof]]
arch = "x86_64"
git-tree-sha1 = "141a09c14b844e183433b9b3e984ef1460a409a6"
os = "windows"

    [[pprof.download]]
    sha256 = "487a6887e4339864789fe31fac8a3bd4032eb46c5544abe7dda5408139a09bc3"
    url = "https://github.com/JuliaBinaryWrappers/pprof_jll.jl/releases/download/pprof-v2.0.0+0/pprof.v2.0.0.x86_64-w64-mingw32.tar.gz"
