[[pprof]]
arch = "aarch64"
git-tree-sha1 = "f14a4d30d17f5ff4dd07cee030775f514a29710d"
os = "macos"

    [[pprof.download]]
    sha256 = "b6ac92e9cb1ca88b6e92563abcc5850bdf2513386d99a9d4797fc6b12bd17ec3"
    url = "https://github.com/JuliaBinaryWrappers/pprof_jll.jl/releases/download/pprof-v0.1.1+0/pprof.v0.1.1.aarch64-apple-darwin.tar.gz"
[[pprof]]
arch = "aarch64"
git-tree-sha1 = "b900fbf8b793ba8c3ead10cba99b954e63acea93"
libc = "glibc"
os = "linux"

    [[pprof.download]]
    sha256 = "8b6850e3d7285a95d803639252d39b9049d53418b168d00467b48d9ab47938bf"
    url = "https://github.com/JuliaBinaryWrappers/pprof_jll.jl/releases/download/pprof-v0.1.1+0/pprof.v0.1.1.aarch64-linux-gnu.tar.gz"
[[pprof]]
arch = "aarch64"
git-tree-sha1 = "ce9502e83c8848f10dbed1bd81c57e03b478eeea"
libc = "musl"
os = "linux"

    [[pprof.download]]
    sha256 = "08890d16ce9c9b877ea1b723565288ad6b9872e55c1d64055afcfb770ecb5a40"
    url = "https://github.com/JuliaBinaryWrappers/pprof_jll.jl/releases/download/pprof-v0.1.1+0/pprof.v0.1.1.aarch64-linux-musl.tar.gz"
[[pprof]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7a2a60941cf32226cc741c8c385c0d509c0f7fe0"
libc = "glibc"
os = "linux"

    [[pprof.download]]
    sha256 = "73e55a465d650b53bc5789944fcf375713ce1d8dbebe7d3f7d87b45b7ba9fb1b"
    url = "https://github.com/JuliaBinaryWrappers/pprof_jll.jl/releases/download/pprof-v0.1.1+0/pprof.v0.1.1.armv6l-linux-gnueabihf.tar.gz"
[[pprof]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "449e941e62034e209d97800ce4f9644bcf97ca24"
libc = "musl"
os = "linux"

    [[pprof.download]]
    sha256 = "512b363e944b3a85c30f725255f9fff09b25a19ddd09707e2ff609c24b7b274e"
    url = "https://github.com/JuliaBinaryWrappers/pprof_jll.jl/releases/download/pprof-v0.1.1+0/pprof.v0.1.1.armv6l-linux-musleabihf.tar.gz"
[[pprof]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f669a5efb61ee59c962c86fbc5337db2600b4bdf"
libc = "glibc"
os = "linux"

    [[pprof.download]]
    sha256 = "ec55ab7af9964b2c6efc904dca6cb60058b7f2c85c06bf0f1b8d74682487cd85"
    url = "https://github.com/JuliaBinaryWrappers/pprof_jll.jl/releases/download/pprof-v0.1.1+0/pprof.v0.1.1.armv7l-linux-gnueabihf.tar.gz"
[[pprof]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1f2e95415b80b83538e8f1dbdd25f19442aab0e2"
libc = "musl"
os = "linux"

    [[pprof.download]]
    sha256 = "88a518f38fb299d6f7494ff3a00e6b530d75ef01f2b8b3b775187d7c1e989878"
    url = "https://github.com/JuliaBinaryWrappers/pprof_jll.jl/releases/download/pprof-v0.1.1+0/pprof.v0.1.1.armv7l-linux-musleabihf.tar.gz"
[[pprof]]
arch = "i686"
git-tree-sha1 = "b205c06b8547d29b3c45089ff8419f41445c22a0"
libc = "glibc"
os = "linux"

    [[pprof.download]]
    sha256 = "365ecdfb84cd326c00617452476b73ce81ed7b75950244169f71f25c28c7c55d"
    url = "https://github.com/JuliaBinaryWrappers/pprof_jll.jl/releases/download/pprof-v0.1.1+0/pprof.v0.1.1.i686-linux-gnu.tar.gz"
[[pprof]]
arch = "i686"
git-tree-sha1 = "b383712fbeb9011e7cdfc7b554495b983b601960"
libc = "musl"
os = "linux"

    [[pprof.download]]
    sha256 = "ca41a2307284f27cf872ec559b8bf3bbd394c99760db170e65af903503b197ea"
    url = "https://github.com/JuliaBinaryWrappers/pprof_jll.jl/releases/download/pprof-v0.1.1+0/pprof.v0.1.1.i686-linux-musl.tar.gz"
[[pprof]]
arch = "i686"
git-tree-sha1 = "6935b7edcb5f6aba609aa9647ffd2e107e053a4f"
os = "windows"

    [[pprof.download]]
    sha256 = "7d9c62818aef7c41e609d3d9aee6421dc2889ae1e1818411dc960ae1cfae6ffa"
    url = "https://github.com/JuliaBinaryWrappers/pprof_jll.jl/releases/download/pprof-v0.1.1+0/pprof.v0.1.1.i686-w64-mingw32.tar.gz"
[[pprof]]
arch = "powerpc64le"
git-tree-sha1 = "94f1ded51abfbf7c952202d2281ed07e9b051adf"
libc = "glibc"
os = "linux"

    [[pprof.download]]
    sha256 = "5daa9123a0b31d5480c8f9b70410f1f414a13a386f17c102333b950c302b3f57"
    url = "https://github.com/JuliaBinaryWrappers/pprof_jll.jl/releases/download/pprof-v0.1.1+0/pprof.v0.1.1.powerpc64le-linux-gnu.tar.gz"
[[pprof]]
arch = "x86_64"
git-tree-sha1 = "11e9052733a363f12aa47f7f5f1bb24a8001d245"
os = "macos"

    [[pprof.download]]
    sha256 = "ac61e8de43cd29827fa4db046368a91e31d75ed5f2d6e823fcc3ba285885af12"
    url = "https://github.com/JuliaBinaryWrappers/pprof_jll.jl/releases/download/pprof-v0.1.1+0/pprof.v0.1.1.x86_64-apple-darwin.tar.gz"
[[pprof]]
arch = "x86_64"
git-tree-sha1 = "d8880b06e7fc77afb8b4becfc8281a20636472ec"
libc = "glibc"
os = "linux"

    [[pprof.download]]
    sha256 = "675aaa1753174adcd580576575469dbb8080246ba2a2a23521266e6e5be23a15"
    url = "https://github.com/JuliaBinaryWrappers/pprof_jll.jl/releases/download/pprof-v0.1.1+0/pprof.v0.1.1.x86_64-linux-gnu.tar.gz"
[[pprof]]
arch = "x86_64"
git-tree-sha1 = "0aae7cdca1ad17cb888258918e7c7868f4ff997a"
libc = "musl"
os = "linux"

    [[pprof.download]]
    sha256 = "3750da71559de78e1bab8c4473bc9c8331bd06608ad8c0c8b0d36e4780e10be4"
    url = "https://github.com/JuliaBinaryWrappers/pprof_jll.jl/releases/download/pprof-v0.1.1+0/pprof.v0.1.1.x86_64-linux-musl.tar.gz"
[[pprof]]
arch = "x86_64"
git-tree-sha1 = "a0226beef2ee318851fee70e8cfa68087823e65d"
os = "freebsd"

    [[pprof.download]]
    sha256 = "93a0f3d20420b1258bfc1fd28b523f048d54c077058bb2b96715b84e6438a558"
    url = "https://github.com/JuliaBinaryWrappers/pprof_jll.jl/releases/download/pprof-v0.1.1+0/pprof.v0.1.1.x86_64-unknown-freebsd.tar.gz"
[[pprof]]
arch = "x86_64"
git-tree-sha1 = "603f7cae07bcf7d4d28280f7d8b56a6e091e1fb1"
os = "windows"

    [[pprof.download]]
    sha256 = "ba10b7674c61490fa53b72dba0b5b8863f8c7f24350c9e361ec315ca37e4192d"
    url = "https://github.com/JuliaBinaryWrappers/pprof_jll.jl/releases/download/pprof-v0.1.1+0/pprof.v0.1.1.x86_64-w64-mingw32.tar.gz"
