[[pprof]]
arch = "aarch64"
git-tree-sha1 = "429ca9dd78bef047a7bec5ff8673310c21af1e6b"
os = "macos"

    [[pprof.download]]
    sha256 = "7f335d74992428f550a3e80600a9a9c63e522f9dd4fa68714fe482675991d3bd"
    url = "https://github.com/JuliaBinaryWrappers/pprof_jll.jl/releases/download/pprof-v1.0.0+0/pprof.v1.0.0.aarch64-apple-darwin.tar.gz"
[[pprof]]
arch = "aarch64"
git-tree-sha1 = "57adc2bc9dc719e35e4fbac5e0f1cdb8191225a9"
libc = "glibc"
os = "linux"

    [[pprof.download]]
    sha256 = "c35f2ec27f08d5c9d8c6a5479448bd48cd9ba1201fec06e74bb8dff6dba341cc"
    url = "https://github.com/JuliaBinaryWrappers/pprof_jll.jl/releases/download/pprof-v1.0.0+0/pprof.v1.0.0.aarch64-linux-gnu.tar.gz"
[[pprof]]
arch = "aarch64"
git-tree-sha1 = "ed94b14bbcbbab8230a62c248488d5e49bb99b7a"
libc = "musl"
os = "linux"

    [[pprof.download]]
    sha256 = "9f0211aa6e3d55df97c157b93347467914e752215a3c137b583a3b0569fd312e"
    url = "https://github.com/JuliaBinaryWrappers/pprof_jll.jl/releases/download/pprof-v1.0.0+0/pprof.v1.0.0.aarch64-linux-musl.tar.gz"
[[pprof]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "788dde5059c94fdac9c70fab8d3752594eeefd24"
libc = "glibc"
os = "linux"

    [[pprof.download]]
    sha256 = "59808267d7907f86b306fc5fe6ad5de79c89d34f2644686d0405bd9974048efb"
    url = "https://github.com/JuliaBinaryWrappers/pprof_jll.jl/releases/download/pprof-v1.0.0+0/pprof.v1.0.0.armv6l-linux-gnueabihf.tar.gz"
[[pprof]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d038c79685ff3709a97918df3a5624fc299edaa4"
libc = "musl"
os = "linux"

    [[pprof.download]]
    sha256 = "8ed55f9f5a2053d9a22fdf716df8d79bce23605f9cd0acbb7fa0cd1148a93555"
    url = "https://github.com/JuliaBinaryWrappers/pprof_jll.jl/releases/download/pprof-v1.0.0+0/pprof.v1.0.0.armv6l-linux-musleabihf.tar.gz"
[[pprof]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "eb41e09446ebfdb60b681882a7cc398b5c2b139e"
libc = "glibc"
os = "linux"

    [[pprof.download]]
    sha256 = "8d4b811b237e0648c48da3cbe2b9bbb423f95a506f3d20e201340179e372092a"
    url = "https://github.com/JuliaBinaryWrappers/pprof_jll.jl/releases/download/pprof-v1.0.0+0/pprof.v1.0.0.armv7l-linux-gnueabihf.tar.gz"
[[pprof]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "256168cc975733f8479e465b2791daaf112c6880"
libc = "musl"
os = "linux"

    [[pprof.download]]
    sha256 = "980ab4f3c978375d42216e3f07542c1ac01333fe7563a554d054a526f4b2f0e2"
    url = "https://github.com/JuliaBinaryWrappers/pprof_jll.jl/releases/download/pprof-v1.0.0+0/pprof.v1.0.0.armv7l-linux-musleabihf.tar.gz"
[[pprof]]
arch = "i686"
git-tree-sha1 = "c67eb861e26ba5e26890f5f654de934d2d61a367"
libc = "glibc"
os = "linux"

    [[pprof.download]]
    sha256 = "fa1a47958ab844d4138c4b917ffb17d7da2d0e0a46958dd3ddd16c16d2da772c"
    url = "https://github.com/JuliaBinaryWrappers/pprof_jll.jl/releases/download/pprof-v1.0.0+0/pprof.v1.0.0.i686-linux-gnu.tar.gz"
[[pprof]]
arch = "i686"
git-tree-sha1 = "c210e410ad33e45b5fff4616f781217c0b765e0e"
libc = "musl"
os = "linux"

    [[pprof.download]]
    sha256 = "a98aa3c410caf5495a56672e357ae0225b7e595589a3f0b6f37affed356444bc"
    url = "https://github.com/JuliaBinaryWrappers/pprof_jll.jl/releases/download/pprof-v1.0.0+0/pprof.v1.0.0.i686-linux-musl.tar.gz"
[[pprof]]
arch = "i686"
git-tree-sha1 = "cc6203316fdbf5ec74e7c7f9bfe06cd87eebec9b"
os = "windows"

    [[pprof.download]]
    sha256 = "3fd7f749ace96115d66316be490b9f8a67566bb6afe437a0d6a4d489356f76e3"
    url = "https://github.com/JuliaBinaryWrappers/pprof_jll.jl/releases/download/pprof-v1.0.0+0/pprof.v1.0.0.i686-w64-mingw32.tar.gz"
[[pprof]]
arch = "powerpc64le"
git-tree-sha1 = "e70a306bd7551b20e0016bee56d5b33ab5df84dc"
libc = "glibc"
os = "linux"

    [[pprof.download]]
    sha256 = "93c76d68674e5656d4f9ee54cf2b5d4f78f18ed638d84025ac9bf313ddcb82ff"
    url = "https://github.com/JuliaBinaryWrappers/pprof_jll.jl/releases/download/pprof-v1.0.0+0/pprof.v1.0.0.powerpc64le-linux-gnu.tar.gz"
[[pprof]]
arch = "x86_64"
git-tree-sha1 = "f541cf2d6bf0f85deda9e6a7ec3aa5bd44d81deb"
os = "macos"

    [[pprof.download]]
    sha256 = "57039744ca6b2627eb8b49787606d57744827e7ae12a82a0f2399887f5a0d617"
    url = "https://github.com/JuliaBinaryWrappers/pprof_jll.jl/releases/download/pprof-v1.0.0+0/pprof.v1.0.0.x86_64-apple-darwin.tar.gz"
[[pprof]]
arch = "x86_64"
git-tree-sha1 = "373d20d2dd1459e5066c22ec847146e85dfe6818"
libc = "glibc"
os = "linux"

    [[pprof.download]]
    sha256 = "dbec880579fe4391ee26454ff8d816f0a8bd9d0ddabc476fac83bf83d3c14038"
    url = "https://github.com/JuliaBinaryWrappers/pprof_jll.jl/releases/download/pprof-v1.0.0+0/pprof.v1.0.0.x86_64-linux-gnu.tar.gz"
[[pprof]]
arch = "x86_64"
git-tree-sha1 = "76180cf4cacaa80ff1d407a1a02bae958b487344"
libc = "musl"
os = "linux"

    [[pprof.download]]
    sha256 = "521e5f18b424e26d9a1aae48d8826e2f08b3d3322ec0bc86ffdf9cea7a43718d"
    url = "https://github.com/JuliaBinaryWrappers/pprof_jll.jl/releases/download/pprof-v1.0.0+0/pprof.v1.0.0.x86_64-linux-musl.tar.gz"
[[pprof]]
arch = "x86_64"
git-tree-sha1 = "97b179cc447f330ddb963f2ad46f8a3cf7f87e6d"
os = "freebsd"

    [[pprof.download]]
    sha256 = "3e075370768c452156db25533151737be960c4b910cb77010a1599c871cbf26a"
    url = "https://github.com/JuliaBinaryWrappers/pprof_jll.jl/releases/download/pprof-v1.0.0+0/pprof.v1.0.0.x86_64-unknown-freebsd.tar.gz"
[[pprof]]
arch = "x86_64"
git-tree-sha1 = "37b2be9a290efa9fec96884aba6ab5f4a560eb97"
os = "windows"

    [[pprof.download]]
    sha256 = "71d008cf4a4078587653a40b77c78d5e2f578b3494a3b5ff7e4b3b7d1a73fd40"
    url = "https://github.com/JuliaBinaryWrappers/pprof_jll.jl/releases/download/pprof-v1.0.0+0/pprof.v1.0.0.x86_64-w64-mingw32.tar.gz"
