[[pprof]]
arch = "aarch64"
git-tree-sha1 = "f8578049332ce7edfe82122f234487ad35e2713e"
os = "macos"

    [[pprof.download]]
    sha256 = "32260c3bdff3dd11543faf9b35b23da9b4809c88ab90e884ce502d41d5ed3a2b"
    url = "https://github.com/JuliaBinaryWrappers/pprof_jll.jl/releases/download/pprof-v1.0.1+0/pprof.v1.0.1.aarch64-apple-darwin.tar.gz"
[[pprof]]
arch = "aarch64"
git-tree-sha1 = "ba5a6317a832bfd52fb57e715d92f206a7b8ebe5"
libc = "glibc"
os = "linux"

    [[pprof.download]]
    sha256 = "0e0b55bf73436a67a6878a7d799612bc270e037cddd780adce87e363c0bae2c7"
    url = "https://github.com/JuliaBinaryWrappers/pprof_jll.jl/releases/download/pprof-v1.0.1+0/pprof.v1.0.1.aarch64-linux-gnu.tar.gz"
[[pprof]]
arch = "aarch64"
git-tree-sha1 = "ba5a6317a832bfd52fb57e715d92f206a7b8ebe5"
libc = "musl"
os = "linux"

    [[pprof.download]]
    sha256 = "0e0b55bf73436a67a6878a7d799612bc270e037cddd780adce87e363c0bae2c7"
    url = "https://github.com/JuliaBinaryWrappers/pprof_jll.jl/releases/download/pprof-v1.0.1+0/pprof.v1.0.1.aarch64-linux-musl.tar.gz"
[[pprof]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d99529ccc8905184802c89fdc33d32289300ffb8"
libc = "glibc"
os = "linux"

    [[pprof.download]]
    sha256 = "e6ee840b15566b2186f1ef7cc41fd5b14ac2950ae6e58e627847ed30ff5e2dd2"
    url = "https://github.com/JuliaBinaryWrappers/pprof_jll.jl/releases/download/pprof-v1.0.1+0/pprof.v1.0.1.armv6l-linux-gnueabihf.tar.gz"
[[pprof]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d99529ccc8905184802c89fdc33d32289300ffb8"
libc = "musl"
os = "linux"

    [[pprof.download]]
    sha256 = "e6ee840b15566b2186f1ef7cc41fd5b14ac2950ae6e58e627847ed30ff5e2dd2"
    url = "https://github.com/JuliaBinaryWrappers/pprof_jll.jl/releases/download/pprof-v1.0.1+0/pprof.v1.0.1.armv6l-linux-musleabihf.tar.gz"
[[pprof]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "937f08287d7b3abe4929657c194f946848cc0114"
libc = "glibc"
os = "linux"

    [[pprof.download]]
    sha256 = "b2af2fcf5ace3082d0e38b1753bc9e7c05f2069d5977e333a9423b37dc9930b4"
    url = "https://github.com/JuliaBinaryWrappers/pprof_jll.jl/releases/download/pprof-v1.0.1+0/pprof.v1.0.1.armv7l-linux-gnueabihf.tar.gz"
[[pprof]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "937f08287d7b3abe4929657c194f946848cc0114"
libc = "musl"
os = "linux"

    [[pprof.download]]
    sha256 = "b2af2fcf5ace3082d0e38b1753bc9e7c05f2069d5977e333a9423b37dc9930b4"
    url = "https://github.com/JuliaBinaryWrappers/pprof_jll.jl/releases/download/pprof-v1.0.1+0/pprof.v1.0.1.armv7l-linux-musleabihf.tar.gz"
[[pprof]]
arch = "i686"
git-tree-sha1 = "75e5ccb5babec1cf7cea5af97b70ff5a1c392f1a"
libc = "glibc"
os = "linux"

    [[pprof.download]]
    sha256 = "1690003c42513c330619747ca5008664797028a0a4be9089bbb8e8933ac675a5"
    url = "https://github.com/JuliaBinaryWrappers/pprof_jll.jl/releases/download/pprof-v1.0.1+0/pprof.v1.0.1.i686-linux-gnu.tar.gz"
[[pprof]]
arch = "i686"
git-tree-sha1 = "75e5ccb5babec1cf7cea5af97b70ff5a1c392f1a"
libc = "musl"
os = "linux"

    [[pprof.download]]
    sha256 = "1690003c42513c330619747ca5008664797028a0a4be9089bbb8e8933ac675a5"
    url = "https://github.com/JuliaBinaryWrappers/pprof_jll.jl/releases/download/pprof-v1.0.1+0/pprof.v1.0.1.i686-linux-musl.tar.gz"
[[pprof]]
arch = "i686"
git-tree-sha1 = "61a1a0e15ec8d695a620e1138ffc6b1da0a25f61"
os = "windows"

    [[pprof.download]]
    sha256 = "22c4b8156701459357bae5b08289a20492ace94c77c703d04a011781b22816af"
    url = "https://github.com/JuliaBinaryWrappers/pprof_jll.jl/releases/download/pprof-v1.0.1+0/pprof.v1.0.1.i686-w64-mingw32.tar.gz"
[[pprof]]
arch = "powerpc64le"
git-tree-sha1 = "2cdc2d818adf3c8b5cf6aedffd761385a08a3df6"
libc = "glibc"
os = "linux"

    [[pprof.download]]
    sha256 = "84104fb89c370d96acb7843ebba73d7ba1eb5ae14494f18cd50a920952ba9471"
    url = "https://github.com/JuliaBinaryWrappers/pprof_jll.jl/releases/download/pprof-v1.0.1+0/pprof.v1.0.1.powerpc64le-linux-gnu.tar.gz"
[[pprof]]
arch = "x86_64"
git-tree-sha1 = "746da476a085e8a7d4fd84f225bcb8eba2f04e3f"
os = "macos"

    [[pprof.download]]
    sha256 = "c31c7736b7770227ae20c13c154e8afb7c27f4a7d9d56dd020323763f0f3d5dc"
    url = "https://github.com/JuliaBinaryWrappers/pprof_jll.jl/releases/download/pprof-v1.0.1+0/pprof.v1.0.1.x86_64-apple-darwin.tar.gz"
[[pprof]]
arch = "x86_64"
git-tree-sha1 = "c13be74a313e5b0d58c651c54b95de63814e0057"
libc = "glibc"
os = "linux"

    [[pprof.download]]
    sha256 = "fb7e253cd931266a0faee2afd26a4a6bd18abc5a852bb7480bb631a4f498a554"
    url = "https://github.com/JuliaBinaryWrappers/pprof_jll.jl/releases/download/pprof-v1.0.1+0/pprof.v1.0.1.x86_64-linux-gnu.tar.gz"
[[pprof]]
arch = "x86_64"
git-tree-sha1 = "2cbc74955ebcbc8580784ec8ae716a076ade6a60"
libc = "musl"
os = "linux"

    [[pprof.download]]
    sha256 = "fd99f8b963486cbf32c9018cc68e0ba7353044d53cec28678e799a1b1dc4a436"
    url = "https://github.com/JuliaBinaryWrappers/pprof_jll.jl/releases/download/pprof-v1.0.1+0/pprof.v1.0.1.x86_64-linux-musl.tar.gz"
[[pprof]]
arch = "x86_64"
git-tree-sha1 = "cb04f05e2ee220eec560167cc113ae342adf11cd"
os = "freebsd"

    [[pprof.download]]
    sha256 = "8ebcd480b1f0e7f9612d43f4a9f68e0a6f467f41754668fdab57b1c6ab584c92"
    url = "https://github.com/JuliaBinaryWrappers/pprof_jll.jl/releases/download/pprof-v1.0.1+0/pprof.v1.0.1.x86_64-unknown-freebsd.tar.gz"
[[pprof]]
arch = "x86_64"
git-tree-sha1 = "369324d17493886bdc0dbbf5823ae067a7946ef9"
os = "windows"

    [[pprof.download]]
    sha256 = "51cc47fa5ff9797691dd2105ac7a9dba815d1009613cf64e62cfb5fb997df576"
    url = "https://github.com/JuliaBinaryWrappers/pprof_jll.jl/releases/download/pprof-v1.0.1+0/pprof.v1.0.1.x86_64-w64-mingw32.tar.gz"
