# Autogenerated wrapper script for pprof_jll for i686-w64-mingw32
export pprof

JLLWrappers.@generate_wrapper_header("pprof")
JLLWrappers.@declare_executable_product(pprof)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_executable_product(
        pprof,
        "bin\\pprof.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
